# ----- REINVENT4 TOML input for transfer learning -----
run_type = "transfer_learning"
device = "cuda:0"
tb_logdir = "tb_TL_scd1"
json_out_config = "_tl_scd1.json"

[parameters]
# --- training schedule ---
num_epochs = 3
save_every_n_epochs = 1
batch_size = 64
num_refs = 0                 
sample_batch_size = 128      


input_model_file = "/home/cm1202/Desktop/NIH_Project/priors/reinvent.prior"
smiles_file = "scd1_curated_clean.smi"
validation_smiles_file = "scd1_curated_clean.smi"
output_model_file = "prior_scd1.model"

# pairs.type = "tanimoto"
# pairs.upper_threshold = 1.0
# pairs.lower_threshold = 0.7
# pairs.min_cardinality = 1
# pairs.max_cardinality = 199
